server:
  port: 2002

spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.231.140:8840
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.231.140:3306/seata_storage?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

seata:
  enabled: true
  application-id: storage_service
  tx-service-group: default_tx_group #事务分组配置（在v1.5之后默认值为default_tx_group）
  #enable-auto-data-source-proxy: false
  config:
    type: nacos
    nacos:
      server-addr: 192.168.231.140:8840
      group : SEATA_GROUP
      namespace: 075a6da6-bb4b-476f-8b2d-21bb56881c00
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.231.140:8840
      group: SEATA_GROUP
      username: nacos
      password: nacos
      application: seata-server
  service:
    vgroup-mapping:
      default_tx_group: default #


feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
