server:
  port: 9003


spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.231.140:3333

management:
  endpoints:
    web:
      exposure:
        include: '*'
