server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
    appname: eureka-service
    prefer-ip-address: true #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 1 #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-expiration-duration-in-seconds: 2 #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时剔除服务
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/  # 集群配置 互相注册

  server:
    # 关闭自我保护机制，保证不可用服务被及时剔除，默认是true
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000




