server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.231.140:3333
    sentinel:
      transport:
        dashboard: 192.168.231.140:8080
        port: 8719



service-url:
  nacos-user-service: http://nacos-payment-provider

# 激活Sentinel对Fegin的支持
feign:
  sentinel:
    enabled: true