server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com  #eureka 服务端的实例名称 eureka7001
    prefer-ip-address: true #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 1 #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-expiration-duration-in-seconds: 2 #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时剔除服务
    appname: eureka-service
  client:
    register-with-eureka: false #false 表示不向注册中心注册自己
    fetch-registry: false        #false表示自己端就是注册中心我的职责即使维护服务实例，并不需要去检索服务
    service-url:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  单机模式
      defaultZone: http://eureka7002.com:7002/eureka/ # 集群模式 多个eureka相互注册
  server:
    # 关闭自我保护机制，保证不可用服务被及时剔除，默认是true
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000



